project_token: b06c516d96b0e0ee87228d9a
name: TuriActivityClassifier
jobs:
  - job_id: 503061e8-6bea-4b8d-99b8-c6d1e7939834
    language: python
    name: activity_classifier
    entrypoint: activity_classifier_main.py
